name: Upload release artifacts

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.event.release.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  OUT_FOLDER: ${{ github.event.repository.name }}
  EXECUTABLE_NAME: ${{ github.event.repository.name }}
  GO_VERSION: '1.23'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        OS: ["windows/amd64", "linux/amd64"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "OS_GOOS=$(echo ${{ matrix.OS }} | cut -d "/" -f 1)" >> $GITHUB_ENV
        echo "OS_GOARCH=$(echo ${{ matrix.OS }} | cut -d "/" -f 2)" >> $GITHUB_ENV
      shell: bash

    - name: Sanity check
      run: |
        echo "Version: ${{ env.VERSION }}"
        echo "Repository name: ${{ env.REPO_NAME }}"
        echo "Out folder: ${{ env.OUT_FOLDER }}"
        echo "Executable name: ${{ env.EXECUTABLE_NAME }}"
        echo "Go version: ${{ env.GO_VERSION }}"
        echo "OS: ${{ matrix.OS }}"
        echo "OS_GOOS: ${{ env.OS_GOOS }}"
        echo "OS_GOARCH: ${{ env.OS_GOARCH }}"
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build ${{ env.OS_GOOS }}/${{ env.OS_GOARCH }}
      run: GOOS=${{ env.OS_GOOS }} GOARCH=${{ env.OS_GOARCH }} go build -o ${{ env.EXECUTABLE_NAME }}.exe -ldflags "-X main.Version=${{ env.VERSION }}"
      shell: bash

    - name: Create archive
      run: zip ${{ env.OUT_FOLDER}}.zip ${{ env.EXECUTABLE_NAME }} ${{ env.EXECUTABLE_NAME }}.exe
      shell: bash

    - name: Upload artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUT_FOLDER }}.zip
        asset_name: "${{ env.REPO_NAME }}-${{ env.OS_GOOS }}-${{ env.OS_GOARCH }}-${{ env.VERSION }}.zip"
        tag: ${{ github.ref }}